[2024-05-21T03:08:47.368+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_pipeline.create_table scheduled__2024-05-20T00:00:00+00:00 [queued]>
[2024-05-21T03:08:47.390+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_pipeline.create_table scheduled__2024-05-20T00:00:00+00:00 [queued]>
[2024-05-21T03:08:47.391+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-05-21T03:08:47.419+0000] {taskinstance.py:2214} INFO - Executing <Task(PostgresOperator): create_table> on 2024-05-20 00:00:00+00:00
[2024-05-21T03:08:47.434+0000] {standard_task_runner.py:60} INFO - Started process 57 to run task
[2024-05-21T03:08:47.442+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'stock_pipeline', 'create_table', 'scheduled__2024-05-20T00:00:00+00:00', '--job-id', '450', '--raw', '--subdir', 'DAGS_FOLDER/stock_pipeline.py', '--cfg-path', '/tmp/tmpixt6met3']
[2024-05-21T03:08:47.461+0000] {standard_task_runner.py:88} INFO - Job 450: Subtask create_table
[2024-05-21T03:08:48.095+0000] {task_command.py:423} INFO - Running <TaskInstance: stock_pipeline.create_table scheduled__2024-05-20T00:00:00+00:00 [running]> on host 4ceaa523915d
[2024-05-21T03:08:48.391+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='stocks' AIRFLOW_CTX_DAG_ID='stock_pipeline' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-05-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-20T00:00:00+00:00'
[2024-05-21T03:08:48.394+0000] {sql.py:276} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS stock(
            code VARCHAR(5) PRIMARY KEY,
            reference_price FLOAT(2),
            celling_price FLOAT(2),
            floor_price FLOAT(2),
            price FLOAT(2),
            volume FLOAT(2),
            total_volume FLOAT(2),
            total_value BIGINT,
            highest_price FLOAT(2),
            lowest_price FLOAT(2),
            average_price FLOAT(2),
            created_time DATETIME
            );
          
[2024-05-21T03:08:48.646+0000] {base.py:83} INFO - Using connection ID 'postgres_demo' for task execution.
[2024-05-21T03:08:48.670+0000] {base.py:83} INFO - Using connection ID 'postgres_demo' for task execution.
[2024-05-21T03:08:49.181+0000] {sql.py:457} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS stock(
            code VARCHAR(5) PRIMARY KEY,
            reference_price FLOAT(2),
            celling_price FLOAT(2),
            floor_price FLOAT(2),
            price FLOAT(2),
            volume FLOAT(2),
            total_volume FLOAT(2),
            total_value BIGINT,
            highest_price FLOAT(2),
            lowest_price FLOAT(2),
            average_price FLOAT(2),
            created_time DATETIME
            );
          , parameters: None
[2024-05-21T03:08:49.252+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/common/sql/hooks/sql.py", line 404, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/common/sql/hooks/sql.py", line 462, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedObject: type "datetime" does not exist
LINE 14:             created_time DATETIME
                                  ^

[2024-05-21T03:08:49.501+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=stock_pipeline, task_id=create_table, execution_date=20240520T000000, start_date=20240521T030847, end_date=20240521T030849
[2024-05-21T03:08:50.018+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 450 for task create_table (type "datetime" does not exist
LINE 14:             created_time DATETIME
                                  ^
; 57)
[2024-05-21T03:08:50.093+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-21T03:08:50.204+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.11/site-packages/***/models/baseoperator.py:1201: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-05-21T03:08:50.389+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
